// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymejlmipzttjxuknfedv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltZWpsbWlwenR0anh1a25mZWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU3NzUsImV4cCI6MjA2NTU4MTc3NX0.LTiwbDT_VrxbrXExfqqvnLC1mcfEQ9p9HNoYdfro1L4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);